#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
#platform :ios, '8.0'

target 'AmahiAnywhere' do

use_frameworks!
    pod 'Alamofire', '~> 4.7'
#    pod 'Alamofire'
    pod 'MBProgressHUD'
    pod 'EVReflection/Alamofire'
    pod 'IQKeyboardManagerSwift'
    pod 'SkyFloatingLabelTextField'
    pod 'MobileVLCKit'
    pod 'Lightbox'
    pod 'ReachabilitySwift'
end
